### ISSUE TITLE
System.IO.FileNotFoundException on server share paths over 255 charracters...

### ISSUE THREAD

**Issue by jeliss** [RichardD2/NTFS-Streams#5]
When using .net 4.6.2 (which fixes accessing long file names/paths)
I'm using the \\\\?\UNC\server\share\Verrrrrrrrrrrry long path syntax.

https://blogs.msdn.microsoft.com/jeremykuhne/2016/06/21/more-on-new-net-path-handling/
https://stackoverflow.com/questions/5188527/how-to-deal-with-files-with-a-name-longer-than-259-characters

I get:

System.IO.FileNotFoundException: The filename, directory name, or volume label syntax is incorrect. (Exception from HRESULT: 0x8007007B)
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   at Trinet.Core.IO.Ntfs.SafeNativeMethods.ThrowIOError(Int32 errorCode, String path)
   at Trinet.Core.IO.Ntfs.SafeNativeMethods.ThrowLastIOError(String path)
   at Trinet.Core.IO.Ntfs.SafeNativeMethods.SafeGetFileAttributes(String name)
   at Trinet.Core.IO.Ntfs.FileSystem.AlternateDataStreamExists(FileSystemInfo file, String streamName)

looks like public static string BuildStreamPath(string filePath, string streamName) isn't handling if it is a server share vs local drive.

**Comment by RichardD2** [comment]
I can't get the built-in IO APIs to accept a path with the long path prefix, even with 4.7.1 installed. `File.Exists(@"\\?\C:\some\file.txt")` always returns `false` even if the file exists, and `Path.GetFullPath(@"\\?\C:\some\file.txt")` or `new FileInfo(@"\\?\C:\some\file.txt")` throws an "illegal characters in path" exception.

However, I've updated the code to use the `GetFileAttributes` method (instead of `File.Exists`) to test whether the file exists, and to avoid creating a `FileInfo` when you pass in a string path, so you should now be able to pass in the path with or without the prefix. 

I've tested locally, and it also seems to work with the `\\?\UNC\...` prefix. *(For some reason, I couldn't get it to work using my machine name, but using the IP address works fine. `Directory.GetFiles` had the same problem, so I suspect it's an issue on my PC.)* 

**NB:** You will need to add the long UNC prefix manually. The code will currently only add the `\\?\` prefix to the path; it doesn't automatically detect UNC paths and adjust the prefix accordingly. *(Let me know if you think it should!)*

There seemed to be a problem accessing the ADS on a folder, since the stream name was including the trailing `\` character. This should also be fixed.

Finally, I've also updated the NuGet package with multi-targeting, so you can now use it from .NET Standard 2.0 projects. *(Obviously the P/Invoke calls will only work on Windows.)*

v4.1.1 is [up on NuGet](https://www.nuget.org/packages/Trinet.Core.IO.Ntfs/) now, or you can grab commit 68a511f.

**Comment by FaustoNascimento** [comment]
@RichardD2 this totally works as of 4.6.2, so long as your project targets 4.6.2 or higher (which this one doesn't).

If it doesn't, then you need to change the config file, as per [this blog](https://blogs.msdn.microsoft.com/jeremykuhne/2016/06/21/more-on-new-net-path-handling/)

Because they removed the restrictions around how the path needs to be written, you can now also use the .NET to directly access an ADS using (for example) `File.ReadAllLines(@"\\?\C:\file.txt:stream")`

The only thing I don't think can be done using .NET as of 4.6.2 is list ADS.

**Comment by jeliss** [comment]
Confirmed 4.6.2 or higher it works fine.
